language: python

# This could be useful
#sudo: required
#services:
#- docker
#before_install:
#- docker pull ccoffrin/coursera_mzn_env

python:
- "2.7"
- "3.5"
install: 
- "pip install pytest"
- "pip install pytest-cov"
script: 
- "py.test"
