language: python
python:
  - "2.7"
  - "3.5"
install: 
  - "pip install pytest pytest-cov"
  - "pip install coveralls"
script: 
  - "py.test --doctest-modules --cov submit --cov-report term-missing"
after_success:
  - "coveralls"
